dubbo:
  scan:
    base-packages: com.lwq.example.cloud.dubbo
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
feign:
  hystrix:
    enabled: true

spring:
  profiles:
    active: nacos
