dubbo:
#  cloud:
#    subscribed-services: ${provider.application.name}
  registry:
    #   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://172.16.20.220
  protocols:
    dubbo:
      port: -1
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181
server:
  port: 8081

#provider:
#  application:
#    name: dubbo-provider