spring:
  application:
    name: business-service

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.20.220:8848
    alibaba:
      seata:
        tx-service-group: business-service
    loadbalancer:
      ribbon:
        enabled: true
    sentinel:
      transport:
        dashboard: 172.16.20.220:8080
        clientIp: 172.16.20.4
      datasource:
        ds1:
          file:
            file: "classpath: flowrule.json"
            data-type: json
            rule-type: flow

server:
  port: 18081



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# The following configuration can be omitted.
feign:
#  hystrix:
#    enabled: true
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000


logging:
  level:
    io.seata: debug
seata:
  enabled: true
  service:
    vgroup-mapping:
      business-service: default
    grouplist:
      default: 172.16.20.220:8091
    disable-global-transaction: false

## if use registry center
#seata.registry.type=nacos
#seata.registry.nacos.cluster=default
#seata.registry.nacos.server-addr=localhost
#
## if use config center
#seata.config.type=apollo
#seata.config.apollo.apollo-meta=http://192.168.1.204:8801
#seata.config.apollo.app-id=seata-server
