server:
  port: 8088

spring:
  application:
    name: springboot-rabbitmq-delayqueue

  # 连接rabbitmq
  rabbitmq:
    host: 172.16.20.220
    port: 5672
    username: guest
    password: guest
    virtual-host: /myvhost

    template:
      mandatory: true



